#!/bin/bash
#
# global bashrc
#
# include from the local .bashrc
#

set -o vi

SCRIPTDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# read in mycd if available
[ -r $SCRIPTDIR/../mycd.sh ] && . $SCRIPTDIR/../mycd.sh

# maven bash
[ -r $SCRIPTDIR/..maven_bash_completion.bash ] && . $SCRIPTDIR/../maven_bash_completion.bash


# $1  how many times we should go up in the directory hierarchy. Defaults to 3 if not specified.
up()
{
   cnt=${1:-3}   # default to 'up 3'
   # want to only perform one 'cd', so that 'cd -' works
   str=$(eval "printf '/..'%.0s {1..$cnt}")  # http://rosettacode.org/wiki/Repeat_a_string
   cd "."$str
}

# git grep
gg() {
   [ -z "$1" -o -z "$2" ] && { echo "Usage: gg <search string> <file glob>"; return 1; }
   search=$1
   glob=$2
   shift 2
   git grep $@ "$search" -- "$glob"
}

# git-delbranch <branchname>
git-delbranch()
{
  git branch -D $1 && git push origin :$1
}


################################
#
# aliases
#
################################
alias gs="git status"
alias up2="up 2"
alias up3="up 3"


